version: "3.8"
services:
  web:
    build: .
    ports:
      - "21001:3000"
    environment:
      - REQUEST_RATE_LIMIT=5
      - RANDOM_COUNT=10
      - LOSS_THRESHOLD=10
      - DELAY_THRESHOLD=500
    env_file:
      - .env.local
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs